function(AddUnityTarget TARGET_NAME)
    set(UNITY_BUILD_FILE ${CMAKE_CURRENT_BINARY_DIR}/${TARGET_NAME}_unity.cpp)
    
    file(WRITE ${UNITY_BUILD_FILE} "// Unity build generated by CMake\n\n")
    foreach(SRC_FILE ${ARGN})
        file(APPEND ${UNITY_BUILD_FILE} "#include \"${SRC_FILE}\"\n")
    endforeach()
    
    if(WIN32)
        add_executable(${TARGET_NAME} WIN32 ${UNITY_BUILD_FILE})
    endif(WIN32)

    if(UNIX)
        add_executable(${TARGET_NAME} ${UNITY_BUILD_FILE})
    endif(UNIX)

    
    target_include_directories(${TARGET_NAME} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})
endfunction()

file(GLOB_RECURSE GAME_ENGINE_SOURCES CONFIGURE_DEPENDS 
	"${CMAKE_SOURCE_DIR}/Source/Application/*.cpp"
	"${CMAKE_SOURCE_DIR}/Source/Engine/GraphicsEngine/*.cpp" 
	"${CMAKE_SOURCE_DIR}/Source/Engine/GraphicsEngine/Material/*.cpp" 
	"${CMAKE_SOURCE_DIR}/Source/Engine/GraphicsEngine/GraphicCommands/*.cpp" 
	"${CMAKE_SOURCE_DIR}/Source/Engine/GameEngine/Components/*.cpp"
	"${CMAKE_SOURCE_DIR}/Source/Engine/GameEngine/*.cpp" 
	"${CMAKE_SOURCE_DIR}/Source/Utilities/CommonUtilities/*.cpp" 
	"${CMAKE_SOURCE_DIR}/Source/Networking/Client/Client.cpp"
	"${CMAKE_SOURCE_DIR}/Source/Networking/Server/Server.cpp"
)

list(REMOVE_ITEM GAME_ENGINE_SOURCES "${CMAKE_SOURCE_DIR}/Source/Engine/GraphicsEngine/Texture.cpp")